/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'steven' at '09/12/16 23:40' with Gradle 3.2.1
 *
 * @author steven, @date 09/12/16 23:40
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
